services:
    app.security.encoder.generator:
        class: AppBundle\Security\Encoder\BaseGenerator
    app.security.encoder.password:
        class: AppBundle\Security\Encoder\PasswordEncoder
        arguments:
            - @app.security.encoder.generator